const resList = [
  {
    type: "restaurant",
    info: {
      id: "334475",
      name: "KFC",
      cloudinaryImageId: "bdcd233971b7c81bf77e1fa4471280eb",
      imageUrl: "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=600&h=400&fit=crop",
      cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
      costForTwo: 40000,
      costForTwoString: "₹400 FOR TWO",
      deliveryTime: 36,
      slaString: "36 MINS",
      avgRating: "3.8",
      totalRatings: 500,
      locality: "BTM Layout",
      area: "BTM Layout",
      veg: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    info: {
      id: "229",
      name: "Meghana Foods",
      cloudinaryImageId: "xqwpuhgnsaf18te7zvtv",
      imageUrl: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&h=400&fit=crop",
      cuisines: ["Biryani", "Andhra", "South Indian", "North Indian", "Chinese", "Seafood"],
      costForTwo: 50000,
      costForTwoString: "₹500 FOR TWO",
      deliveryTime: 29,
      slaString: "29 MINS",
      avgRating: "4.4",
      totalRatings: 1000,
      locality: "Koramangala",
      area: "Koramangala",
      veg: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    info: {
      id: "121603",
      name: "Kannur Food Point",
      cloudinaryImageId: "bmwn4n4bn6n1tcpc8x2h",
      imageUrl: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600&h=400&fit=crop",
      cuisines: ["Kerala", "Chinese"],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 31,
      slaString: "31 MINS",
      avgRating: "3.8",
      totalRatings: 5000,
      locality: "SG Palya",
      area: "Tavarekere",
      veg: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    info: {
      id: "500001",
      name: "Subway",
      imageUrl: "https://images.unsplash.com/photo-1509722747041-616f39b57569?w=600&h=400&fit=crop",
      cuisines: ["Sandwich", "Salads", "Wraps", "Healthy Food"],
      costForTwo: 35000,
      costForTwoString: "₹350 FOR TWO",
      deliveryTime: 25,
      slaString: "25 MINS",
      avgRating: "4.1",
      totalRatings: 3200,
      locality: "Indiranagar",
      area: "Indiranagar",
      veg: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    info: {
      id: "500002",
      name: "Domino's Pizza",
      imageUrl: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&h=400&fit=crop",
      cuisines: ["Pizza", "Italian", "Pasta", "Desserts"],
      costForTwo: 40000,
      costForTwoString: "₹400 FOR TWO",
      deliveryTime: 30,
      slaString: "30 MINS",
      avgRating: "4.2",
      totalRatings: 8500,
      locality: "HSR Layout",
      area: "HSR Layout",
      veg: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    info: {
      id: "500003",
      name: "Pizza Hut",
      imageUrl: "https://images.unsplash.com/photo-1594007654729-407eedc4be65?w=600&h=400&fit=crop",
      cuisines: ["Pizza", "Pasta", "Wings", "Italian"],
      costForTwo: 60000,
      costForTwoString: "₹600 FOR TWO",
      deliveryTime: 35,
      slaString: "35 MINS",
      avgRating: "3.9",
      totalRatings: 4100,
      locality: "Jayanagar",
      area: "Jayanagar",
      veg: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    info: {
      id: "500004",
      name: "McDonald's",
      imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&h=400&fit=crop",
      cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
      costForTwo: 35000,
      costForTwoString: "₹350 FOR TWO",
      deliveryTime: 22,
      slaString: "22 MINS",
      avgRating: "4.3",
      totalRatings: 12000,
      locality: "MG Road",
      area: "MG Road",
      veg: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    info: {
      id: "500005",
      name: "Burger King",
      imageUrl: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=600&h=400&fit=crop",
      cuisines: ["Burgers", "American", "Fast Food"],
      costForTwo: 35000,
      costForTwoString: "₹350 FOR TWO",
      deliveryTime: 28,
      slaString: "28 MINS",
      avgRating: "4.0",
      totalRatings: 6200,
      locality: "Whitefield",
      area: "Whitefield",
      veg: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    info: {
      id: "500006",
      name: "Taco Bell",
      imageUrl: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&h=400&fit=crop",
      cuisines: ["Mexican", "Fast Food", "Snacks"],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 33,
      slaString: "33 MINS",
      avgRating: "3.6",
      totalRatings: 1800,
      locality: "Electronic City",
      area: "Electronic City",
      veg: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    info: {
      id: "500007",
      name: "Barbeque Nation",
      imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&h=400&fit=crop",
      cuisines: ["North Indian", "BBQ", "Kebabs", "Biryani"],
      costForTwo: 150000,
      costForTwoString: "₹1500 FOR TWO",
      deliveryTime: 45,
      slaString: "45 MINS",
      avgRating: "4.5",
      totalRatings: 9800,
      locality: "JP Nagar",
      area: "JP Nagar",
      veg: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    info: {
      id: "500008",
      name: "Starbucks Coffee",
      imageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&h=400&fit=crop",
      cuisines: ["Coffee", "Beverages", "Snacks", "Desserts"],
      costForTwo: 40000,
      costForTwoString: "₹400 FOR TWO",
      deliveryTime: 20,
      slaString: "20 MINS",
      avgRating: "4.2",
      totalRatings: 7500,
      locality: "Church Street",
      area: "Brigade Road",
      veg: true,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    info: {
      id: "500009",
      name: "Haldiram's",
      imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&h=400&fit=crop",
      cuisines: ["North Indian", "South Indian", "Sweets", "Chinese", "Street Food"],
      costForTwo: 45000,
      costForTwoString: "₹450 FOR TWO",
      deliveryTime: 27,
      slaString: "27 MINS",
      avgRating: "4.1",
      totalRatings: 4500,
      locality: "Marathahalli",
      area: "Marathahalli",
      veg: true,
    },
    subtype: "basic",
  },
];

export default resList;
